### ISSUE TITLE
Support for nzpy in place of pyodbc

### ISSUE THREAD

**Issue by ravte** [IBM/nzalchemy#3]
The documentation specifically mentions this package works only with pyodbc. 
Please support nzpy as well.

**Comment by abhishekjog** [comment]
@ravte we are working on it.

**Comment by bkief** [comment]
+1

**Comment by shabbir10july** [comment]
Draft PR: https://github.com/IBM/nzalchemy/pull/5

**Comment by shabbir10july** [comment]
Test summary with nzpy:

```
================================================ short test summary info =================================================
FAILED test/test_suite.py::AutocommitTest_nzdbapi+netezza_11_2_1::test_autocommit_on - AssertionError: 1 != None
FAILED test/test_suite.py::AutocommitTest_nzdbapi+netezza_11_2_1::test_turn_autocommit_off_via_default_iso_level - Asse...
FAILED test/test_suite.py::NumericTest_nzdbapi+netezza_11_2_1::test_numeric_null_as_decimal - TypeError: conversion fro...
================================= 3 failed, 164 passed, 169 skipped in 69.39s (0:01:09) ==================================

```

**Comment by shireenrao** [comment]
The nzalchemy driver using pyodbc currently doesnt let me read json columns. I tried PR #5 by @shabbir10july and it works beautifully. This would be a great addition! Can this please be merged?

**Comment by abhishekjog** [comment]
@shireenrao, yes. That PR is being reviewed and will be merged soon. We had added JSON datatypes in nzpy sometime back, good to know that is working for you!
